version: '3'
services:
  api:
    build: ./Docker/go
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./backend:/go/src/work
    command: sh -c "go run *.go"
    depends_on:
      - db

  db:
    build: ./Docker/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./Docker/postgres/setup:/usr/local/src

  web:
    build: ./Docker/react
    volumes:
      - ./frontend/:/usr/src/app
    command: sh -c "cd web && npm start"
    ports:
      - "3000:3000"