version: '3'
services:
  api:
    build: ./Docker/go
    ports:
      - "23450:23450"
    tty: true
    volumes:
      - ./api:/go/src/work
    command: sh -c "go run *.go"
    depends_on:
      - db

  db:
    build: ./Docker/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./Docker/postgres/setup:/usr/local/src

  nginx:
    image: nginx:latest
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/src:/var/www/html
    depends_on:
      - php

  php:
    build: ./Docker/php
    volumes:
      - ./frontend/src:/var/www/html
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
      - redis

  mysql:
    build: ./Docker/mysql
    working_dir: /usr/local/src
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./Docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./Docker/mysql/sql:/var/local/src/sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"