version: '3'
services:
  api:
    build: ./Docker/go
    ports:
      - "23450:23450"
    tty: true
    volumes:
      - ./backend:/go/src/work
    command: sh -c "go run *.go"
    depends_on:
      - db

  db:
    build: ./Docker/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./Docker/postgres/setup:/usr/local/src

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html
    depends_on:
      - php

  php:
    build: ./Docker/php
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    depends_on:
      - db